hoauth2.cabal
src/Network/OAuth/OAuth2/Internal.hs

Issue #33 .
Sorry this also contains another commit. I do not know how to cherry-pick on github. Wishing you could reject it from your side.

Add "expires_in" and "token_type" to AccessToken for Google.

---

example/Fitbit/test.hs
example/Keys.hs.sample
hoauth2.cabal

Hi Wu,
this implementation contains server as well. Did you think about similar implementation in https://github.com/freizl/hoauth2/issues/37 or how did you mean that?
I can maybe add server to other examples as well if you like it this way.
Rene

Fitbit example

---

example/run-7.6.sh
example/run.sh
hoauth2.cabal
src/Network/OAuth/OAuth2.hs
src/Network/OAuth/OAuth2/HttpClient.hs
src/Network/OAuth/OAuth2/Internal.hs

This is just some cleanup stuff. It should allow you to end up with Haddock on hackage. Hope it's useful.

cleaned up documentation; fixed minor source nits

---

.gitignore
Makefile
example/Dropbox/test.hs
example/Keys.hs.sample
hoauth2.cabal
src/Network/OAuth/OAuth2/HttpClient.hs
src/Network/OAuth/OAuth2/Internal.hs

- do not send both auth in the request body and header but always in
header when fetch access request.

Fixed issue #38

---

LICENSE
example/Douban/test.hs
example/Dropbox/test.hs
example/Facebook/test.hs
example/Fitbit/test.hs
example/Github/test.hs
example/Google/test.hs
example/Keys.hs.sample
example/StackExchange/test.hs
example/Weibo/test.hs
hoauth2.cabal
src/Network/OAuth/OAuth2/HttpClient.hs
src/Network/OAuth/OAuth2/Internal.hs
stack.yaml

I've replaced most `String`/`Text`/`ByteString` with typed variants, anything that's coming in via JSON is decoded into `Text`. I've changed `AccessToken` to `OAuth2Token`, and `AccessToken` is now the `access_token` in `OAuth2Token`.
This PR will require a rewrite of any code using it, should I just fork and go for hoauth3?
Tests:

Typing it up

---

example/Douban/test.hs
example/Dropbox/test.hs
example/Facebook/test.hs
example/Fitbit/test.hs
example/Github/test.hs
example/Google/test.hs
example/StackExchange/test.hs
example/Weibo/test.hs
hoauth2.cabal
src/Network/OAuth/OAuth2/AuthorizationRequest.hs
src/Network/OAuth/OAuth2/HttpClient.hs
src/Network/OAuth/OAuth2/Internal.hs
src/Network/OAuth/OAuth2/TokenRequest.hs
stack.yaml

Not fully tested. Apropos, does travis do all the API requests?

Typing up oauth error messages

---

Makefile
example/Api.hs
src/Network/OAuth/OAuth2/HttpClient.hs

use record wildcards

---

src/Network/OAuth/OAuth2/Internal.hs

This PR addresses issue #64.
Microsoft's Azure AD OAuth2 token response returns the `expires_in` field as a string, god bless them. This makes `OAuth2Token` parsing more flexible.

Flexibly parse expires_in on OAuth2Token from string

---

example/IDP.hs
example/IDP/AzureAD.hs
example/Keys.hs.sample
example/README.md
hoauth2.cabal
src/Network/OAuth/OAuth2/Internal.hs

Add AzureAD example to demo app

---

src/Network/OAuth/OAuth2/Internal.hs

Makes the code compile on GHC 8.2.2.

add (<>) include

---

hoauth2.cabal

Allows to build with Stackage Nightly.

Relax binary and wai-middleware-static versions

---

hoauth2.cabal
hoauth2.nix
src/Network/OAuth/OAuth2/HttpClient.hs

To fix https://github.com/freizl/hoauth2/issues/109

Add method refreshToken2

---

Makefile
example/App.hs
example/IDP.hs
example/IDP/AzureAD.hs
example/IDP/Douban.hs
example/IDP/Dropbox.hs
example/IDP/Facebook.hs
example/IDP/Fitbit.hs
example/IDP/Github.hs
example/IDP/Google.hs
example/IDP/Okta.hs
example/IDP/StackExchange.hs
example/IDP/Weibo.hs
example/IDP/ZOHO.hs
example/Keys.hs.sample
example/README.md
example/Types.hs
example/templates/index.mustache
hoauth2.cabal

Add another refresh token method and add Soho integration

---

hoauth2.cabal
hoauth2.nix
src/Network/OAuth/OAuth2/Internal.hs

- Solve https://github.com/freizl/hoauth2/issues/112
- Given another thoughts, add `Eq` to all those newtype are more appropriate.

Add eq instance

---

cabal.project
hoauth2-demo/.gitignore
hoauth2-demo/Makefile
hoauth2-demo/hoauth2-demo.cabal
hoauth2-demo/public/templates/index.mustache
hoauth2-demo/src/App.hs
hoauth2-demo/src/Idp.hs
hoauth2/src/Network/OAuth2/Experiment/Types.hs

- This is the grant type that google service account uses
- Spec https://www.rfc-editor.org/rfc/rfc7523.html#section-2.1
fixes #16, #51

Add GrantType jwt-bearer

---

hoauth2-demo/src/Idp.hs
hoauth2-providers/src/Network/OAuth2/Provider/AzureAD.hs
hoauth2/src/Network/OAuth/OAuth2/Internal.hs

Update oauth2 and user info endpoint for Azure

---

hoauth2-demo/src/Idp.hs
hoauth2-demo/src/Types.hs
hoauth2/src/Network/OAuth2/Experiment/Types.hs

Fixes https://github.com/freizl/hoauth2/issues/167

Move HasIdpName class to hoauth2-demo

---

hoauth2-demo/src/Idp.hs
hoauth2-providers/hoauth2-providers.cabal
hoauth2-providers/src/Data/ByteString/Contrib.hs
hoauth2-providers/src/Network/OAuth2/Provider/Auth0.hs
hoauth2-providers/src/Network/OAuth2/Provider/AzureAD.hs
hoauth2-providers/src/Network/OAuth2/Provider/Dropbox.hs
hoauth2-providers/src/Network/OAuth2/Provider/Facebook.hs
hoauth2-providers/src/Network/OAuth2/Provider/Fitbit.hs
hoauth2-providers/src/Network/OAuth2/Provider/Google.hs
hoauth2-providers/src/Network/OAuth2/Provider/Linkedin.hs
hoauth2-providers/src/Network/OAuth2/Provider/Okta.hs
hoauth2-providers/src/Network/OAuth2/Provider/Slack.hs
hoauth2-providers/src/Network/OAuth2/Provider/StackExchange.hs
hoauth2-providers/src/Network/OAuth2/Provider/Weibo.hs
hoauth2/src/Network/OAuth2/Experiment.hs

Move Provider.Utils to Data.ByteString.Contrib

---

hoauth2-demo/hoauth2-demo.cabal
hoauth2-providers-tutorial/hoauth2-providers-tutorial.cabal
hoauth2-providers/hoauth2-providers.cabal
hoauth2-tutorial/hoauth2-tutorial.cabal
hoauth2/hoauth2.cabal

bump to text-2.0

---

cabal.project
hoauth2-demo/src/App.hs
hoauth2-demo/src/Idp.hs
hoauth2-providers-tutorial/src/HOAuth2ProvidersTutorial.hs
hoauth2-providers/src/Network/OAuth2/Provider/Auth0.hs
hoauth2-providers/src/Network/OAuth2/Provider/AzureAD.hs
hoauth2-providers/src/Network/OAuth2/Provider/Okta.hs

- init Azure IdP information base on well-known endpoint
- Also remove `defaultAuth0Idp`, `defaultAzureADIdp`, `defaultOktaIdp` which are not useful.

Add mkAzureADIdp helper

---

Makefile
hoauth2-demo/hoauth2-demo.cabal
hoauth2-demo/public/templates/index.mustache
hoauth2-demo/src/App.hs
hoauth2-demo/src/Idp.hs
hoauth2-demo/src/Types.hs
hoauth2-providers-tutorial/hoauth2-providers-tutorial.cabal
hoauth2-providers/hoauth2-providers.cabal
hoauth2-providers/src/Network/OAuth2/Provider/Auth0.hs
hoauth2-providers/src/Network/OAuth2/Provider/AzureAD.hs
hoauth2-providers/src/Network/OAuth2/Provider/Dropbox.hs
hoauth2-providers/src/Network/OAuth2/Provider/Facebook.hs
hoauth2-providers/src/Network/OAuth2/Provider/Fitbit.hs
hoauth2-providers/src/Network/OAuth2/Provider/Github.hs
hoauth2-providers/src/Network/OAuth2/Provider/Google.hs
hoauth2-providers/src/Network/OAuth2/Provider/Linkedin.hs
hoauth2-providers/src/Network/OAuth2/Provider/Okta.hs
hoauth2-providers/src/Network/OAuth2/Provider/Slack.hs
hoauth2-providers/src/Network/OAuth2/Provider/StackExchange.hs
hoauth2-providers/src/Network/OAuth2/Provider/Twitter.hs
hoauth2-providers/src/Network/OAuth2/Provider/Weibo.hs
hoauth2-providers/src/Network/OAuth2/Provider/ZOHO.hs
hoauth2-tutorial/hoauth2-tutorial.cabal
hoauth2/hoauth2.cabal
hoauth2/src/Network/OAuth2/Experiment.hs
hoauth2/src/Network/OAuth2/Experiment/Flows/DeviceAuthorizationRequest.hs
hoauth2/src/Network/OAuth2/Experiment/GrantType.hs
hoauth2/src/Network/OAuth2/Experiment/GrantType/DeviceAuthorization.hs
hoauth2/src/Network/OAuth2/Experiment/Types.hs

1. Fixes #161 
- Create `design-notes.org` to capture some thoughts
1. the current design:  `public app -> flow request data type -> request body` conversion.
3. some type class only has one instance, probably will be forever
4. limitation on the `TokenRequestError`

Device Authorization grant

---

hoauth2-demo/public/templates/index.mustache
hoauth2-demo/src/App.hs
hoauth2-demo/src/Env.hs
hoauth2-demo/src/Idp.hs
hoauth2-demo/src/Types.hs
hoauth2-demo/src/Utils.hs
hoauth2-providers/src/Network/OAuth2/Provider/Google.hs
hoauth2-providers/src/Network/OAuth2/Provider/Okta.hs
hoauth2/src/Network/OAuth2/Experiment/Grants/ClientCredentials.hs

- Be able to read credential from env.json for device-auth, password, client credentials grant
- for ClientCredentials flow, client_id isn't required with Basic Auth but required with jwt assertion.

Slight better to way init device app

---

hoauth2/src/Network/OAuth2/Experiment/Flows/RefreshTokenRequest.hs
hoauth2/src/Network/OAuth2/Experiment/Grants/AuthorizationCode.hs
hoauth2/src/Network/OAuth2/Experiment/Grants/ResourceOwnerPassword.hs

- really not necessary
fixes #226

Remove data family `RefreshTokenRequest`

---

hoauth2-demo/hoauth2-demo.cabal
hoauth2-demo/src/Session.hs
hoauth2-demo/src/Types.hs
hoauth2-providers/hoauth2-providers.cabal
hoauth2-providers/src/Network/OAuth2/Provider.hs

Data.Map is probably good enough for demo-app

---

hoauth2-tutorial/hoauth2-tutorial.cabal
hoauth2-tutorial/src/HOAuth2ExperimentTutorial.hs

Add tutorial for using Experiment module

---

cabal.project
hoauth2-demo/hoauth2-demo.cabal
hoauth2-providers-tutorial/hoauth2-providers-tutorial.cabal
hoauth2-providers/hoauth2-providers.cabal
hoauth2-tutorial/hoauth2-tutorial.cabal
hoauth2/hoauth2.cabal
hoauth2/src/Network/OAuth2/Experiment/Pkce.hs

1. [x] bump the package to 1.0
2. [x] manual test on pkce flows
To fix https://github.com/commercialhaskell/stackage/issues/7279

Upgrade base64 to 1.0

---

hoauth2-demo/hoauth2-demo.cabal
hoauth2-demo/src/App.hs
hoauth2-providers-tutorial/hoauth2-providers-tutorial.cabal
hoauth2-providers-tutorial/src/HOAuth2ProvidersTutorial.hs
hoauth2-providers/hoauth2-providers.cabal
hoauth2-tutorial/hoauth2-tutorial.cabal
hoauth2-tutorial/src/HOAuth2ExperimentTutorial.hs
hoauth2-tutorial/src/HOAuth2Tutorial.hs
hoauth2/hoauth2.cabal

Fixes https://github.com/commercialhaskell/stackage/issues/7661

Bump to uri-bytestring-0.4

---

.gitignore
hoauth2-demo/.gitignore
hoauth2-demo/dev.org
hoauth2-demo/hoauth2-demo.cabal
hoauth2-demo/public/templates/index.mustache
hoauth2-demo/sample.env.json
hoauth2-demo/src/App.hs
hoauth2-demo/src/Env.hs
hoauth2-demo/src/Idp.hs
hoauth2-demo/src/Types.hs
hoauth2-demo/src/User.hs
hoauth2-providers/hoauth2-providers.cabal
hoauth2-providers/src/Network/OAuth2/Provider.hs
hoauth2-providers/src/Network/OAuth2/Provider/Facebook.hs
hoauth2-providers/src/Network/OAuth2/Provider/Linear.hs
hoauth2-providers/src/Network/OAuth2/Provider/LinkedIn.hs
hoauth2-providers/src/Network/OAuth2/Provider/StackExchange.hs
hoauth2/hoauth2.cabal
hoauth2/src/Network/OAuth/OAuth2/HttpClient.hs
hoauth2/src/Network/OAuth/OAuth2/Internal.hs

1. Fixes Facebook provider configure
2. Fixes Linkedin provider configure
4. Add Linear provider
5. Refactor StacxExchange by passing the key
6. A few refactor to the demo app

Refactor idp
